# Generated by Django 5.2.4 on 2025-07-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobanalysis',
            old_name='summary',
            new_name='ai_comment',
        ),
        migrations.RemoveField(
            model_name='job',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='jobanalysis',
            name='score',
        ),
        migrations.AddField(
            model_name='job',
            name='overall_rating',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='line_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='rating',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobanalysis',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
