# Generated by Django 5.2.4 on 2025-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('public_safety', 'Public Safety'), ('road_damage', 'Road Damage'), ('vandalism', 'Vandalism'), ('sanitation', 'Sanitation'), ('lighting', 'Lighting'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
