# Generated by Django 5.2.4 on 2025-07-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reporter',
        ),
    ]
