# Generated by Django 5.2.4 on 2025-07-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_incident_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reporter_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
