# Generated by Django 5.2.4 on 2025-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incident_latitude_incident_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reporter_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
