# Generated by Django 5.2.4 on 2025-08-05 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_remove_comment_author_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvoted_incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
